language: java
sudo: required
before_script:
  - sudo apt-get update
  - sudo apt-get install lib32z1 lib32ncurses5
before_install:
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-3.1.1-unix.tar.gz
  - tar -xzf neo4j-community-3.1.1-unix.tar.gz
  - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-3.1.1/conf/neo4j-server.properties
  - neo4j-community-3.1.1/bin/neo4j start
services:
  - neo4j  
jdk:
  - oraclejdk8
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test
after_success:
  - bash <(curl -s https://codecov.io/bash)
